### ISSUE TITLE
Exception in WebStorm

### ISSUE THREAD

**Issue by jdasilva** [gdelmas/IntelliJDashPlugin#26]
I was testing for [Velocity](http://velocity.silverlakesoftware.com/) integration on Windows and got the following exception using WebStorm (occured in 7.0.3 and fresh install of latest 8.0.4).

cannot create class "de.dreamlab.dash.DashLauncherAction" [Plugin: com.paperetto.dash]: cannot create class "de.dreamlab.dash.DashLauncherAction" [Plugin: com.paperetto.dash]
com.intellij.diagnostic.PluginException: cannot create class "de.dreamlab.dash.DashLauncherAction" [Plugin: com.paperetto.dash]
    at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.a(ActionManagerImpl.java:287)
    at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.a(ActionManagerImpl.java:239)
    at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.getAction(ActionManagerImpl.java:232)
    at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.updateCurrentContext(IdeKeyEventDispatcher.java:679)
    at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.d(IdeKeyEventDispatcher.java:416)
    at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:206)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:493)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:335)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
Caused by: java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
    at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.a(ActionManagerImpl.java:264)
    ... 13 more
Caused by: java.lang.NoClassDefFoundError: com/intellij/sql/dialects/SqlLanguageDialect
    at de.dreamlab.dash.KeywordLookup.<init>(KeywordLookup.java:66)
    at de.dreamlab.dash.DashLauncherAction.<init>(DashLauncherAction.java:32)
    ... 18 more
Caused by: java.lang.ClassNotFoundException: com.intellij.sql.dialects.SqlLanguageDialect PluginClassLoader[com.paperetto.dash, 3.1]
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:68)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 20 more

**Comment by superbogy** [comment]
i get the same error too, I had don't nothing. All jetbrains ide show error when start

**Comment by gdelmas** [comment]
hi @superbogy,

i could not reproduce the issue with WebStorm 2016.1 on windows 7. could you please tell more details.

which version of the plugin are you using?
which version of the which ide are you using?
where did you install the plugin from (repository/manual)?
which operating system are you using?
did the plugin work before? or did you just install it?
is the error reported each time you invoke the shortcut or just once?
is there an error report upon ide startup (please check event window)


thanks for your report,
gerard

**Comment by gdelmas** [comment]
can you also please paste the error message and stacktrace.
